name: proto to openapi

on:
  push:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v3'
      - id: make
        shell: bash
        run: |
          make
      - id: test
        shell: bash
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
          unzip protoc-3.15.8-linux-x86_64.zip -d /usr/local/bin
          protoc --version
          wget https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v2.18.0/protoc-gen-openapiv2-v2.18.0-linux-x86_64
          chmod +x protoc-gen-openapiv2-v2.18.0-linux-x86_64
          sudo mv protoc-gen-openapiv2-v2.18.0-linux-x86_64 /usr/local/bin/protoc-gen-openapiv2
          protoc-gen-openapiv2 --version
